configure.ac
```
libcinnamon-desktop/libgsystem/Makefile-libgsystem.am:20: warning: source file '$(libgsystem_srcpath)/gsystem-local-alloc.c' is in a subdirectory,
libcinnamon-desktop/libgsystem/Makefile-libgsystem.am:20: but option 'subdir-objects' is disabled
libcinnamon-desktop/Makefile.am:22:   'libcinnamon-desktop/libgsystem/Makefile-libgsystem.am' included from here
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the …
```
=> Stop build spam

libcinnamon-desktop/gnome-bg.c, libcinnamon-desktop/gnome-thumbnail-pixbuf-utils.c
Avoid one potential divide by zero, and one case where a pointer could be used before it was set.
=> correct errors detected by scan-build

libcinnamon-desktop/gnome-bg.c
Fixes this warning
```
(cinnamon-settings-daemon:3556): CinnamonDesktop-CRITICAL **: handle_text: assertion 'parser->slides->tail != NULL' failed
(cinnamon-settings-daemon:3556): CinnamonDesktop-CRITICAL **: handle_text: assertion 'parser->slides->tail != NULL' failed
(cinnamon-settings-daemon:3556): CinnamonDesktop-CRITICAL **: handle_text: assertion 'parser->slides->tail != NULL' failed
(cinnamon-settings-daemon:3556): CinnamonDesktop-CRITICAL **: handle_text: assertion 'parser->slides->tail != NULL' failed
(cinnamon-settings-daemon:3556): CinnamonDesktop-CRITICAL **: handle_text: assertion 'parser->slides->tail != NULL' failed
```
Pull origin is from mate-desktop
=> fix xml bg warning

libcinnamon-desktop/gnome-desktop-thumbnail.c
taken from
https://git.gnome.org/browse/gnome-desktop/commit/?id=5b28350d3229d36d7c64084e52f5a40ee5903723
=> thumbnail: Fix a code path where the mutex is never unlocked

autogen.sh, configure.ac, libcinnamon-desktop/Makefile.am, libcvc/Makefile.am
gnome-common is deprecating some vars and macros, listed here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829932
This change follows the gnome recommendations from:
https://wiki.gnome.org/Projects/GnomeCommon/Migration
Please note that this still depends on gnome-common.
=> Migrate away from gnome-common deprecated vars and macros

libcvc/cvc.pc.in
```
'test-media-keys.c' || echo './'`test-media-keys.c
cc1: warning: /usr/include/cvc: No such file or directory [-Wmissing-include-dirs]
```
=> Fix includes for libcvc

data/cinnamon-desktop
A change was made to the pam config file in be51f074f7316195ba376962d52746310ecb99e3 that effectively breaks authorization in cinnamon-screensaver for non Fedora users. The default config should work out-of-the-box on more distros than just Fedora. This change improves cross-distro compatibility by making sure auth doesn't fail just because `pam_selinux_permit.so` is not present on the system. Instead, the auth process will continue trying the remaining modules listed.
Fixes Antergos/antergos-packages#144
>A missing module acts like a “fail”, and the error is logged (via the system logging daemon, usually syslog).
>
>If a line in the configuration file starts with a dash, the error isn't logged.  This can be useful for modules that may not be present, for example, a module for fingerprint …
=> Update pam config for multi-distro compatibility

schemas/org.cinnamon.desktop.interface.gschema.xml.in.in, schemas/org.cinnamon.desktop.wm.preferences.gschema.xml.in.in
We need a couple of new keys to store the original themes in use so we can get
back to them when disabling High Contrast
=> schemas: Add some new keys for High Contrast

libcvc/gvc-mixer-control.c
https://git.gnome.org/browse/libgnome-volume-control/commit/?id=a28e23d9006a32c8982ad8bda11fec131c6b36e8
https://git.gnome.org/browse/libgnome-volume-control/commit/?id=25bf3ed75fa604fa73e8b25241119a993fc659d6
No regressions I can see on speakers, headphones, simple headset. No messages in log. Laptop.  Could probably do with a quick once-over by someone with more exotic kit.
=> gvc-mixer-control: fix double-free when setting headset

libcvc/gvc-mixer-control.c
https://git.gnome.org/browse/libgnome-volume-control/commit/?id=d52194fce13f4b477afc997ff752233aa6886cbf
No regressions I can see on speakers, headphones, simple headset. No messages in log. Laptop.  Could probably do with a quick once-over by someone with more exotic kit.
=> gvc-mixer-control: fix reference being leaked

files/usr/bin/cinnamon-desktop-migrate-mediakeys, installer-test
- Update print statements in cinnamon-desktop-migrate-mediakeys and
installer-test to correctly support python3.
- Update python she-bang lines to use python3 instead of python2.
=> Trivial syntax fixes to support python3.

schemas/org.cinnamon.desktop.notifications.gschema.xml.in.in
This adds an option to move the notification popup to the bottom of the screen.
=> Notifications: Add bottom position option

libcinnamon-desktop/gnome-bg.c
fixes warnings from csd-background
g_variant_unref: assertion 'value != NULL' failed
=> gnome-bg: don't unref NULL gvariant

libcinnamon-desktop/meson.build
In autotools build, pkgconfig version was the project version.
=> Fix pkgconfig version and fix spacing

debian/rules, meson.build, meson_options.txt
Changed the name of deprecated-flags build option to match the one
in nemo and set it to false by default like it was before the meson port.
Also added descriptions. Following the style guidelines here:
https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting
=> Update style of meson build options

schemas/org.cinnamon.desktop.default-applications.gschema.xml.in.in
* Defines a schema that allows users to specify a default calculator application.
* Default initialized to 'gnome-calculator'.
* By itself, this PR does not change much. However, it allows for other relevant PRs to act on the existence of this schema.
* Will open PR at [linuxmint/Cinnamon](https://github.com/linuxmint/Cinnamon) to open a PR to expose a SettingsWidget() in [cs_default.py](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py) to control the schema
* Will open PR at [linuxmint/cinnamon-settings-daemon](https://github.com/linuxmint/cinnamon-settings-daemon) to update [csd-media-key-manager.c](https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/media-keys/csd-media-keys-manager.c) to honor the …
=> default-applications.gschema.xml: Define schema for a default calculator

meson.build, schemas/meson.build
Bump the minimum meson version to something that we needed anyway, and return to using build_by_default which was removed in 05bd02d5af851bab6c83d0969a2dad3a94582b63 due to version pinning.
=> Meson deprecations

libcvc/gvc-mixer-stream.c
Based on https://github.com/GNOME/libgnome-volume-control/commit/9a2996b3626713df80e62b42721f94a5e20e2958
=> Fix unused GIR transfer notation on integer values

libcinnamon-desktop/gnome-wall-clock.c, libcinnamon-desktop/gnome-wall-clock.h
**Problem**
When we use strftime parts of the date (day and month names) are translated according to LC_TIME.
But when we fetch the clock format (which is translated by our translators), we use gettext and that uses LANGUAGE, not LC_TIME. If LANGUAGE and LC_TIME are different we then end up with broken clocks which mix both languages.
Here's a python script (test-cdesktop.py) to illustrate it:
```
#!/usr/bin/python3
import gi
gi.require_version('CinnamonDesktop', '3.0')
from gi.repository import CinnamonDesktop
clock = CinnamonDesktop.WallClock()
print(clock.get_clock().capitalize())
```
Run that with an English LANGUAGE and a Spanish LC_TIME and you get a broken clock:
```
clem@airtop ~/Desktop $ LANGUAGE=es_ES.UTF-8 LC_TIME=en_US.UTF-8 ./test-cdesktop.py
Friday,  4 de october, 14:38
``` …
=> Fetch clock formats using LC_TIME (as opposed to LANGUAGE)

schemas/org.cinnamon.desktop.session.gschema.xml.in.in
For cinnamon-session and cinnamon-settings-daemon.
=> [4.6] org.cinnamon.desktop.session schema: Remove logind/consolekit settings

libcinnamon-desktop/gnome-wall-clock.c
In that case, even though we're not setting the LANGUAGE,
we still need to localize the string with gettext.
=> Clock: Fix date format when LC_TIME=LANGUAGE or LC_TIME=NULL

libcinnamon-desktop/gnome-rr-output-info.c
This fixes a bug with scale calculation for connected but disabled monitors. We don't want to calculate 1/(0/1) ever
=> Fix scale calculation for cinnamon-control-center's display panel

libcinnamon-desktop/gnome-rr-config.c, libcinnamon-desktop/gnome-rr-config.h, libcinnamon-desktop/gnome-rr-private.h, libcinnamon-desktop/gnome-rr.c, libcinnamon-desktop/gnome-rr.h
Various changes for the cinnamon-control-center display module re-introducing 'automatic' ui scale.
see linuxmint/cinnamon-control-center#238
=> Fixes for gnome-rr scaling

libcinnamon-desktop/gnome-rr-config.c
(cleanup, I want to try to help before December when 20.1/Cinnamon 4.8 gets released)
=> gnome-rr-config.c: Remove some unused variables

schemas/org.cinnamon.desktop.default-applications.gschema.xml.in.in
This PR is to update the exec-arg setting for gnome-terminal from '-x' to '--'
=> Changed setting from '-x' to '--'

libcinnamon-desktop/gnome-bg.c
I've noticed that the times at which desktop background transitions take place are off by 1 hour compared to what is specified in the XML files. Increasing the value in the hour field by 1 fixed the issue.
I looked into why, and the culprit is that the value stored in the <hour> field is decremented by 1. Maybe someone assumed hours were being counted from 0 to 23.
Assuming that the code was forked from GNOME, I looked into gnome-desktop, and the issue is noted there, too. (https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/issues/4), and the same fix as the one in this pull request is waiting to be merged (https://gitlab.gnome.org/GNOME/gnome-desktop/-/merge_requests/97).
=> gnome-bg.c: don't decrement hour by 1 when parsing xml backgrounds

libcvc/gvc-channel-map.c, libcvc/gvc-mixer-card.c, libcvc/gvc-mixer-control.c, libcvc/gvc-mixer-event-role.c, libcvc/gvc-mixer-sink-input.c, libcvc/gvc-mixer-sink.c, libcvc/gvc-mixer-source-output.c, libcvc/gvc-mixer-source.c, libcvc/gvc-mixer-stream.c, libcvc/gvc-mixer-ui-device.c
Based on https://github.com/GNOME/libgnome-volume-control/commit/13a4a9a5c2badae9d18b9b437573be5c65b772d7
=> GVC: avoid deprecated g_type_class_add_private

libcinnamon-desktop/gnome-bg.c
Ref: https://github.com/GNOME/gnome-desktop/commit/db0e20607050c7c859446420905cc8680249554a#diff-2449085de556a57f2376e17c247ae29bf6b3f4c60a15b979b494a82c12e6171d
"People might prefix their dates/times with 0 which leads to the number
being interpreted as octal value. This can then lead to "08" being
interpreted as 0, because 8 is not a valid octal value. This is also
much more likely than people intentionally trying to use octal or hex
values for dates/times."
=> Always parse date/time integers in base-10

debian/control, debian/rules, libcinnamon-desktop/gnome-bg-crossfade.c, libcinnamon-desktop/gnome-desktop-thumbnail.c, libcinnamon-desktop/gnome-pnp-ids.c, libcinnamon-desktop/gnome-rr-config.c, libcinnamon-desktop/gnome-rr-labeler.c, libcinnamon-desktop/gnome-rr-output-info.c, libcinnamon-desktop/gnome-rr.c, libcinnamon-desktop/gnome-wall-clock.c, libcinnamon-desktop/gnome-xkb-info.c, meson.build
* Fix build warnings due to deprecated macro G_TYPE_INSTANCE_GET_PRIVATE
* meson: fix minimum version (-> 0.50.0)
* packaging: fix lintian warnings
* priority extra replaced by optional
* removed python dependency for cinnamon-desktop-data (unneeded since #127) and dh-python
* python3 is kept as build dep for `meson_install_schemas.py`
* removed unneeded shlibs substvar for gir packages
=> Fix build warnings

libcinnamon-desktop/cdesktop-enums.h, schemas/org.cinnamon.desktop.notifications.gschema.xml.in
In tandem with linuxmint/cinnamon#11703
Resolves #230
=> Adding an option for notification screen selection

debian/control
- Launchpad and local builds using `debuild` fails due to this missing dependency
=> Add iso-codes as build-depends
